# Generated by Django 4.0.5 on 2022-07-22 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('num_submissions', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('rejection_reason', models.TextField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='bounty_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bounty_images')),
                ('thumb', models.ImageField(null=True, upload_to='bounty_thumbs')),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
                ('completion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.completion')),
            ],
        ),
    ]
