# Generated by Django 3.2.14 on 2022-07-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('ACRITHIA', 'Acrithia'), ('ALLODS', "Allod's Bight"), ('ASHFIELDS', 'Ash Fields'), ('BASIN', 'Basin Sionnach'), ('CALLAHAN', "Callahan's Passage"), ('CALLUMS', "Callum's Cape"), ('CLANSHEAD', 'Clanshead Valley'), ('ENDLESS', 'Endless Shore'), ('FARRANAC', 'Farranac Coast'), ('FISHERMANS', "Fisherman's Row"), ('GODCROFTS', 'Godcrofts'), ('GREATMARCH', 'Great March'), ('HOWL', 'Howl County'), ('KALOKAI', 'Kalokai'), ('LOCH', 'Loch Mór'), ('MARBAN', 'Marban Hollow'), ('MORGENS', "Morgen's Crossing"), ('NEVISH', 'Nevish Line'), ('ORIGIN', 'Origin'), ('REACHING', 'Reaching Trail'), ('REDRIVER', 'Red River'), ('SHACKLED', 'Shackled Chasm'), ('SPEAKING', 'Speaking Woods'), ('STONECRADLE', 'Stonecradle'), ('TEMPEST', 'Tempest Island'), ('TERMINUS', 'Terminus'), ('DEADLANDS', 'The Deadlands'), ('DROWNED', 'The Drowned Vale'), ('FINGERS', 'The Fingers'), ('HEARTLANDS', 'The Heartlands'), ('LINN', 'The Linn of Mercy'), ('MOORS', 'The Moors'), ('OARBREAKER', 'The Oarbreaker Isles'), ('UMBRAL', 'Umbral Wildwood'), ('VIPER', 'Viper Pit'), ('WEATHERED', 'Weathered Expanse'), ('WESTGATE', 'Westgate')], default='ASHFIELDS', max_length=32)),
                ('coordinates', models.CharField(blank=True, max_length=3, null=True)),
                ('jobtype', models.CharField(choices=[('LOGI', 'Logistics'), ('DEMO', 'Demolition'), ('PARTISAN', 'Partisan'), ('CONSTRUCTION', 'Construction'), ('COMBAT', 'Combat'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('rejection_reason', models.TextField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='bounty_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('COLONIAL', 'Colonial'), ('WARDEN', 'Warden')], default='COLONIAL', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warNumber', models.IntegerField()),
                ('winner', models.CharField(max_length=32, null=True)),
                ('startTime', models.IntegerField(blank=True, null=True)),
                ('endTime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='bounty_images')),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
                ('completion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.completion')),
            ],
        ),
        migrations.AddField(
            model_name='completion',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.team'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.team'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='war',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.war'),
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
