# Generated by Django 3.2.14 on 2022-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='endTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='war',
            name='startTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
