# Generated by Django 3.2.14 on 2022-07-26 02:06

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='bounty_images'),
        ),
    ]
