# Generated by Django 4.0.5 on 2022-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_bounty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
