# Generated by Django 3.2.14 on 2022-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20220729_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='jobtype',
            field=models.CharField(choices=[('LOGI', 'Logistics'), ('DEMOLITION', 'Demolition'), ('PARTISAN', 'Partisan'), ('CONSTRUCTION', 'Construction'), ('COMBAT', 'Combat'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
    ]
