# Generated by Django 3.2.14 on 2022-07-30 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_alter_bounty_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=64)),
                ('discordid', models.CharField(default='None', max_length=32)),
                ('types', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BountyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.channel')),
            ],
        ),
    ]
