# Generated by Django 3.2.14 on 2022-07-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_auto_20220722_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='coordinates',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
