# Generated by Django 4.0.5 on 2022-06-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_alter_bounty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='bounty_images'),
        ),
    ]
