# Generated by Django 3.2.14 on 2022-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_bounty_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='job_type',
            field=models.CharField(choices=[('LOGI', 'Logistics'), ('DEMO', 'Demolition'), ('PARTISAN', 'Partisan'), ('CONSTRUCTION', 'Construction'), ('COMBAT', 'Combat'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
    ]
