# Generated by Django 3.2.14 on 2022-08-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_bountynotification_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.team'),
        ),
        migrations.AlterField(
            model_name='bountynotification',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
