# Generated by Django 4.0.5 on 2022-07-01 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0005_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
