# Generated by Django 3.2.14 on 2022-08-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0005_auto_20220801_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discordid', models.CharField(default='None', max_length=32)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
