# Generated by Django 4.0.5 on 2022-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0006_completion_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
