# Generated by Django 3.2.14 on 2022-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0007_delete_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='jobtype',
            field=models.CharField(choices=[('LOGI', 'Logistics'), ('DEMOLITION', 'Demolition'), ('PARTISAN', 'Partisan'), ('CONSTRUCTION', 'Construction'), ('COMBAT', 'Combat'), ('REFUEL', 'Refuel'), ('OTHER', 'Other')], default='OTHER', max_length=12),
        ),
    ]
