# Generated by Django 3.2.14 on 2022-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0007_alter_bounty_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warNumber', models.IntegerField()),
            ],
        ),
    ]
