# Generated by Django 3.2.14 on 2022-07-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0008_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='war',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.war'),
        ),
        migrations.AddField(
            model_name='war',
            name='endTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='war',
            name='startTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='war',
            name='winner',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
