# Generated by Django 3.2.14 on 2022-07-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0010_auto_20220724_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='completion',
            name='longitude',
        ),
    ]
