# Generated by Django 4.0.5 on 2022-07-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0010_remove_bounty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='completion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.completion'),
        ),
        migrations.AlterField(
            model_name='completion',
            name='bounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty'),
        ),
        migrations.AlterField(
            model_name='images',
            name='bounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.bounty'),
        ),
    ]
