# Generated by Django 4.0.5 on 2022-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0011_images_completion_alter_completion_bounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completion',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
