# Generated by Django 3.2.14 on 2022-07-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0011_auto_20220724_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='job_type',
            new_name='jobtype',
        ),
    ]
