# Generated by Django 4.0.5 on 2022-07-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0012_completion_latitude_completion_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='rejection_reason',
            field=models.TextField(null=True),
        ),
    ]
