# Generated by Django 4.0.5 on 2022-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0013_completion_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='thumb',
            field=models.ImageField(null=True, upload_to='bounty_images'),
        ),
    ]
