# Generated by Django 3.2.14 on 2022-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0006_guild'),
        ('users', '0002_auto_20220802_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='dateAuthorized',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='discordToken',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='guilds',
        ),
        migrations.AddField(
            model_name='profile',
            name='dateAuthorized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discordToken',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(to='bounty.Guild'),
        ),
    ]
