# Generated by Django 3.2.14 on 2022-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discordname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
