# Generated by Django 3.2.14 on 2022-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0006_guild'),
        ('users', '0004_auto_20220802_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(blank=True, null=True, to='bounty.Guild'),
        ),
    ]
