# Generated by Django 3.2.14 on 2022-07-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_discordname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discordid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discordname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
