# Generated by Django 3.2.14 on 2022-08-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_guilds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guilds',
        ),
    ]
