# Generated by Django 3.2.14 on 2022-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_guilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
